server:

  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
       -id: order-service
       uri: lb://order-service
       predicates:
         - Path=/api/order/**
       filters:
         - name: CircuitBreaker
           args:
             name: orderServiceCircuitBreaker
             fallbackUri: forward:/fallback/order-service
      -id: pricing-service
      uri: lb://pricing-service
      predicates:
        - Path=/api/pricing/**
      filters:
        - name: CircuitBreaker
          args:
            name: pricingServiceCircuitBreaker
            fallbackUri: forward:/fallback/pricing-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitBreaker:
    configs:
      default:
        failureRateThreshold: 50;
        waitDurationInOpenState: 30s;
        minimumNumberOfCalls: 5
        slidingWindowSize: 10

management:
  endpoints:
    web:
        exposure:
            include: health, gateway

